
const data={
WTCHK:{name:'開舖前，執靚防線',sub:'改造門店',tone:'#167e78',desc:'巡一圈、改一改。令好服務由清晰視線開始。',steps:[
{title:'宣傳架好搶眼，但遮住咗乜？',intro:'開舖前，你發現轉角宣傳架擋住同事視線。先撳場景下方嘅位置，睇清楚問題。',scene:'高陳列令轉角另一側難以看見。',options:['加一張 CCTV 提示牌，保留陳列。','調低遮擋視線嘅陳列，配合同事正常服務覆蓋。','叫一位同事全日留喺轉角。'],correct:1,why:'清晰視線配合員工存在感，先方便觀察同提供協助。提示牌唔能夠消除遮擋。',after:'陳列降低咗，同事可以自然睇到轉角，同顧客打招呼。',win:'你改善咗服務視線。'},
{title:'細件商品，點擺先合適？',intro:'一批小型商品放喺較少同事經過嘅位置，而且容易一次取走大量。你會點調整？',scene:'商品集中放喺偏僻陳列區。',options:['搬到同事較易看見嘅位置，配合合適陳列防護。','所有商品收起，顧客問先逐件拎。','維持陳列，提醒同事有空先行過。'],correct:0,why:'將可見度、服務同合適陳列防護配合使用，可以減少機會，亦保留購物便利。',after:'商品移到較易提供服務嘅位置，陳列亦作出合適調整。',win:'你改善咗商品陳列。'},
{title:'同事問：「要唔要叫佢開袋？」',intro:'同事見到顧客將未付款商品放入個人袋。你要俾佢一個安全、友善嘅行動方向。',scene:'觀察到商品放入個人袋；未能由此判定顧客意圖。',options:['要求顧客打開個人袋，核實先。','暫時唔理，等佢出門再追上去。','先提供購物籃同協助；疑慮持續時保持距離，按程序處理。'],correct:2,why:'先服務，唔指控；唔自行搜袋、追逐或對抗。作為店長，要協調同事按已確認程序處理。',after:'同事友善提供購物籃，保持安全距離；店長準備按程序協調後續。',win:'你帶同事以服務同安全行先。'}]},
PNS:{name:'繁忙一更：你派邊個？',sub:'帶隊調配',tone:'#b35b35',desc:'三個服務時刻，睇你點樣安排一隊好拍檔。',steps:[
{title:'有人查詢，另一區又有情況。',intro:'阿欣正回答顧客問題；貨架區另一位顧客用物件遮擋處理商品嘅動作。阿朗可以協助，你點安排？',scene:'阿欣：處理查詢　｜　阿朗：可以支援',options:['叫阿欣立即放低查詢，去質問另一位顧客。','請阿朗到貨架區友善提供協助，阿欣繼續服務。','兩位同事一齊處理同一個查詢。'],correct:1,why:'分工令服務保持覆蓋；留意同時發生嘅行為，但唔可以直接當成有分工犯案嘅證據。',after:'阿欣繼續解答，阿朗到貨架區提供協助。兩區都有同事存在感。',win:'你保持咗服務覆蓋。'},
{title:'自助付款，仲差一步。',intro:'畫面顯示交易仍未完成，顧客準備推車離開付款區。你指示同事點講？',scene:'自助付款狀態：尚未完成',options:['「你係咪未畀錢？唔可以走。」','等顧客自己發現，唔好打擾。','「你好，付款好似未完成，我幫你核對一下。」'],correct:2,why:'先協助核對商品掃碼、優惠同付款狀態，唔好未確認就假設對方故意漏付。',after:'同事協助核對交易狀態，先處理付款問題，避免誤會。',win:'你用服務處理交易問題。'},
{title:'「店長，我追出去睇吓！」',intro:'疑慮未釐清，相關顧客向出口移動。同事提議追出店外，你要即時俾指示。',scene:'同事正等候你嘅指示。',options:['「唔好追、唔好攔，保持距離；我按程序協調處理。」','「追出去，但唔好碰到佢。」','「企喺出口，等釐清先畀佢離開。」'],correct:0,why:'追逐或阻擋都可能令風險升級。安全比貨品重要；店長要阻止冒險並按 BU 程序尋求指定支援。',after:'同事留喺安全位置，店長按已確認程序處理，避免追逐同阻擋。',win:'你保障咗同事安全。'}]},
FTR:{name:'現場還原：你見到乜？',sub:'觀察解謎',tone:'#5974a8',desc:'翻開觀察卡，分清見到嘅事同心入面嘅估計。',steps:[
{title:'三段畫面，邊項值得多留意？',intro:'先翻開三張觀察卡。你要辨認具體行為，唔係靠外表揀人。',scene:'翻卡了解現場',evidence:['顧客帶住一個大袋，正常行入店內。','顧客比較兩件商品，睇完放回貨架。','顧客用袋遮住手部處理商品嘅動作。'],options:['帶大袋嘅顧客。','比較兩件商品嘅顧客。','用袋遮擋處理商品動作嘅情況。'],correct:2,why:'袋嘅大小唔係證據；實際遮擋商品處理動作先係值得多留意嘅行為，亦未代表已證實不當行為。',after:'你揀出具體可觀察行為，同時保留「仍未確認」嘅判斷。',win:'你分清咗行為同外表。'},
{title:'兩邊同時發生，代表乜？',intro:'翻開三張卡，睇清楚時間關係，再決定應該點理解。',scene:'同一時段嘅三項觀察',evidence:['14:05　一位顧客持續向同事查詢。','14:05　另一位顧客在其他位置遮擋處理商品嘅動作。','尚未確認兩人關係，亦未確認商品有否被取走。'],options:['兩人一定合作，應立即公開指出。','值得留意整體情況，安排友善服務，但未能定論。','未能確定兩人關係，所以完全唔使理。'],correct:1,why:'行為喺時間上配合值得留意，但唔等於證實關係或意圖。主動服務係合適下一步。',after:'店長安排同事提供協助，繼續觀察實際行為，冇公開指控。',win:'你作出咗有根據嘅判斷。'},
{title:'點交代，先幫到同事？',intro:'情況持續，店長需要交代觀察同協調跟進。翻卡重溫，揀最合適嘅指示。',scene:'交代事實，保持安全',evidence:['已觀察：有人查詢，同時另一人遮擋處理商品動作。','未確認：顧客意圖、商品狀態、兩人關係。','安全底線：唔追、唔搜、唔對抗。'],options:['「見到遮擋處理商品嘅動作，未確認情況；保持距離，按程序跟進。」','「佢哋係一伙，跟實到出門為止。」','「攞住個袋先，等我確認。」'],correct:0,why:'客觀講清已知同未知，先可以幫團隊作出合適決定。唔自行搜袋、追逐或接觸阻攔。',after:'同事收到清楚、客觀嘅交代；店長按 BU 已確認程序尋求支援。',win:'你清楚交代並安全帶隊。'}]},
WW:{name:'一句之間：服務接得住',sub:'互動短劇',tone:'#885975',desc:'一句說話，一個下一步。帶同事接住每段對話。',steps:[
{title:'見到放入個人袋，點開口？',intro:'新同事見到顧客將未付款商品放入個人袋，請你教佢點樣接觸。',scene:'新同事：「我唔知點開口先好……」',options:['「你點解將件貨放入自己個袋？」','「你好，需要購物籃嗎？等我幫你拎一個。」','「麻煩你打開個袋俾我睇。」'],correct:1,why:'提供實際購物協助，可以自然增加員工存在感，亦避免由質問開始。',after:'同事：「你好，需要購物籃嗎？」\n顧客：「唔使，我自己睇。」',win:'你示範咗友善開場。'},
{title:'顧客拒絕咗，然後呢？',intro:'顧客拒絕購物籃，繼續行向視線較差嘅位置。拒絕服務本身唔代表不當行為。',scene:'顧客：「唔使，我自己睇。」',options:['「好，有需要可以叫我。」保持可見服務位置；疑慮持續時按程序處理。','「唔用籃嘅話，我唯有一路跟住你。」','顧客話唔使，就完全唔再留意現場。'],correct:0,why:'尊重拒絕，同時保持自然、可見嘅服務。唔緊跟、唔擋路；持續疑慮交由店長按程序協調。',after:'同事退到自然可見嘅服務位置，顧客仍然拒絕協助；店長留意整體情況。',win:'你平衡咗服務同觀察。'},
{title:'「你係咪懷疑我呀？」',intro:'顧客語氣轉急，同事想上前阻擋。作為店長，你會點回應同安排？',scene:'顧客：「你係咪懷疑我呀？」',options:['「如果冇做錯，畀我睇個袋就得。」','叫同事守住出口，自己再解釋。','「唔好意思令你有呢個感覺，我哋係想提供協助。」讓同事保持距離，按程序處理。'],correct:2,why:'平和解釋唔保證對方合作。要同時避免阻擋、搜袋同對抗，保障現場人員安全。',after:'店長平和回應，同事保持距離。顧客未必合作，團隊仍按安全底線及程序跟進。',win:'你喺緊張情況下守住安全底線。'}]}}
let state={bu:null,step:0,answers:[],solved:false,selected:null,opened:[],zone:0};let completed={};try{completed=JSON.parse(localStorage.getItem('shift-completed')||'{}')}catch(e){}
const app=document.getElementById('app');
function retailPhoto(bu, status=''){return `<div class="retail-photo ${bu}" role="img" aria-label="${{WTCHK:'個人護理零售店',PNS:'超市',FTR:'電子產品店',WW:'酒類專門店'}[bu]} AI 寫實概念場景，非真實分店">${status?`<div class="scene-photo-status">${status}</div>`:''}<span class="concept-label">AI 概念場景 · 非真實分店</span></div>`}
function storeSVG(improved=false){return `<svg viewBox="0 0 500 265" role="img" aria-label="模擬門店示意圖${improved?'，改善後視線更清楚':''}"><rect x="35" y="25" width="430" height="215" rx="8" fill="#fafbf5"/><path d="M35 178h430v62H35z" fill="#cbd9bd"/><rect x="59" y="48" width="130" height="100" rx="6" fill="#b7c6a7"/><path d="M64 83h120M64 117h120" stroke="#fafbf5" stroke-width="5"/>${[0,1,2,3].map(i=>`<rect x="${70+i*27}" y="57" width="17" height="24" rx="3" fill="#7f9b72"/><rect x="${70+i*27}" y="92" width="17" height="23" rx="3" fill="#e2c580"/>`).join('')}<rect x="245" y="${improved?129:50}" width="72" height="${improved?44:123}" rx="5" fill="${improved?'#80a66c':'#c88d70'}"/><text x="281" y="${improved?155:97}" text-anchor="middle" font-size="12" fill="white">陳列</text><rect x="350" y="152" width="83" height="43" rx="6" fill="#668971"/><rect x="361" y="133" width="28" height="22" rx="3" fill="#244e42"/><circle cx="390" cy="105" r="14" fill="#dfb58f"/><path d="M373 151v-22q17-15 34 0v22" fill="#176653"/><circle cx="220" cy="154" r="13" fill="#dfb58f"/><path d="M204 202v-28q16-13 32 0v28" fill="#b991b1"/><path d="M211 202v22m18-22v22" stroke="#52645b" stroke-width="7"/>${improved?'<path d="M379 115L244 159" stroke="#578741" stroke-width="3" stroke-dasharray="6 5"/><circle cx="300" cy="62" r="22" fill="#d8ee99"/><path d="m289 62 8 8 15-17" fill="none" stroke="#176653" stroke-width="4"/>':''}<text x="390" y="219" text-anchor="middle" font-size="11" fill="#244e42">服務位置</text></svg>`}
function footer(){return `<div class="foot">學習核心：唔靠估，睇行為 · 唔指控，先服務 · 唔冒險，按程序處理<br>本試玩版使用 AI 寫實概念場景，非真實分店或品牌核准圖片；人物以 AI 寫實圖片配合運鏡、轉場及字幕製成動態示範，並非真人實拍影片。各關嘅具體情況以題目文字為準。各 BU 升級處理角色與程序待內部確認。無需登入，完成標記只儲存喺本機瀏覽器。</div>`}
function home(){state.bu=null;document.documentElement.style.setProperty('--accent','#176653');app.innerHTML=`<section class="hero"><div><div class="eyebrow">STORE MANAGER / LEARNING ARCADE</div><h1>一個決定，<br>一份守護。</h1><p class="muted">你熟悉嘅門店，你帶領嘅一班同事。<br>用三個小任務，練習觀察、服務同安全帶隊。</p><span class="pill">只需點選</span><span class="pill">冇時間限制</span><span class="pill">可以隨時再試</span></div><div class="hero-art">${retailPhoto('WTCHK')}</div></section><div class="sectionhead"><div><div class="eyebrow">CHOOSE YOUR SHIFT</div><h2>今日，你喺邊度當更？</h2></div><span class="muted">4 個 BU · 4 種玩法</span></div><div class="cards">${Object.entries(data).map(([key,b])=>`<button class="bu" style="--tone:${b.tone}" onclick="start('${key}')">${retailPhoto(key)}<div class="card-content"><small>${key} ${completed[key]?'✓ 已完成':''}</small><i></i><h3>${b.name}</h3><p class="muted">${b.desc}</p><div class="arrow"><span>${b.sub} · 3 關</span><span>開始 →</span></div></div></button>`).join('')}</div><div class="notice">BU 場景暫按屈臣氏、百佳、豐澤及 Watson’s Wine 設計。呢個係可操作概念版；未接駁 LMS，唔屬正式認證課程。</div>${footer()}`}
function start(bu){state={bu,step:0,answers:[],solved:false,selected:null,opened:[],zone:0};render();window.scrollTo(0,0)}
function scene(q){if(state.bu==='FTR')return `<div class="scene-label">觀察紀錄 / 撳開全部三張卡</div><div class="tapzone">${q.evidence.map((x,i)=>`<button class="${state.zone===i&&state.opened.includes(i)?'active':''}" onclick="openCard(${i})">${state.opened.includes(i)?'✓':'＋'} 觀察 ${i+1}</button>`).join('')}</div><div class="evidence" aria-live="polite">${state.opened.length?q.evidence[state.zone]:'先撳上面嘅觀察卡，了解已知同未知。'}</div>${retailPhoto(state.bu,state.solved?'✓ 已選擇合適行動 · 結果見下方文字':'')}`;
if(state.bu==='PNS')return `<div class="scene-label">當值安排 / 你係帶隊店長</div>${retailPhoto(state.bu)}<div style="padding:20px;display:grid;gap:14px">${['查詢服務','貨架區','自助付款'].map((name,i)=>`<div style="background:#fff;border-radius:14px;padding:20px;border-left:5px solid ${i===state.step?'#b35b35':'#8da180'}"><strong>${name}</strong><p style="margin:8px 0 0">${state.step===0?(i===0?'◉ 阿欣 · 解答查詢':i===1?(state.solved?'◉ 阿朗 · 主動服務':'需要服務覆蓋'):'正常服務中'):state.step===1?(i===2?(state.solved?'◉ 同事協助核對交易':'！ 付款尚未完成'):'保持服務覆蓋'):(i===0?'店長協調處理':i===1?'同事保持服務':state.solved?'✓ 保持距離，唔追唔攔':'！ 同事提議追出店外')}</p></div>`).join('')}</div><div class="scene-bottom" aria-live="polite">${state.solved?q.after:q.scene}</div>`;
if(state.bu==='WW')return `<div class="scene-label">對話現場 / 你係當值店長</div>${retailPhoto(state.bu)}<div class="bubble">${state.solved?q.after.replaceAll('\n','<br>'):q.scene}</div><div class="person">◉ 虛構情境 · 回應唔代表顧客一定合作</div>`;
return `<div class="scene-label">${state.bu==='PNS'?'帶隊現場 / 每次處理一個服務時刻':'門店巡視 / 撳位置睇一睇'}</div>${retailPhoto(state.bu,state.solved?'✓ 已選擇合適行動 · 結果見下方文字':'')}${state.bu==='WTCHK'?`<div class="tapzone">${['轉角視線','商品陳列','服務位置'].map((s,i)=>`<button class="${state.zone===i?'active':''}" onclick="inspect(${i})">${s}</button>`).join('')}</div>`:''}<div class="scene-bottom" aria-live="polite">${state.solved?q.after:state.bu==='WTCHK'?['模擬任務｜轉角：假設高陳列遮擋同事視線，你會點改善？','模擬任務｜商品區：配合合適防護，同時方便選購。','模擬任務｜服務位置：清楚視線配合同事存在感。'][state.zone]:q.scene}</div>`}
function render(){let b=data[state.bu],q=b.steps[state.step];document.documentElement.style.setProperty('--accent',b.tone);let locked=state.bu==='FTR'&&state.opened.length<3;app.innerHTML=`<div class="toprow"><button class="plain" onclick="home()">← 返回 BU 選擇</button><span class="kicker">${state.bu} · ${b.sub} · ${state.step+1} / 3</span></div><div class="progress" aria-label="第 ${state.step+1} 關，共三關">${[0,1,2].map(i=>`<span class="${i<=state.step?'done':''}"></span>`).join('')}</div><div class="gamegrid"><section class="scene">${scene(q)}</section><section class="question"><div class="eyebrow">MISSION 0${state.step+1}</div><h2>${q.title}</h2><p class="muted">${q.intro}</p>${locked?'<p class="kicker">先翻開三張觀察卡，再作決定。</p>':''}<div>${q.options.map((s,i)=>`<button class="choice ${state.selected===i?(state.solved?'correct':'wrong'):''}" ${state.solved||locked?'disabled':''} onclick="choose(${i})"><span class="letter">${'ABC'[i]}</span><span>${s}</span></button>`).join('')}</div>${state.selected!==null?`<div class="feedback ${state.solved?'':'warn'}" role="status"><strong>${state.solved?'✓ '+q.win:'呢個做法有一個風險。'}</strong><p>${q.why}</p>${state.solved?`<button class="primary" onclick="next()">${state.step===2?'睇當更成果':'下一個任務'} →</button>`:'<span class="kicker">再揀一個做法，試吓點樣改善。</span>'}</div>`:''}</section></div><div class="notice">${state.bu==='FTR'?'觀察唔等於定論。保持客觀，以服務方式接觸。':'安全永遠比貨品重要：唔追出店外、唔自行搜身或翻袋、唔作肢體阻擋或對抗。'}</div>${footer()}`}
function inspect(i){state.zone=i;render()}
function openCard(i){if(!state.opened.includes(i))state.opened.push(i);state.zone=i;render()}
function choose(i){if(state.solved)return;if(state.answers[state.step]===undefined)state.answers[state.step]=i===data[state.bu].steps[state.step].correct;state.selected=i;state.solved=i===data[state.bu].steps[state.step].correct;render()}
function next(){if(!state.solved)return;if(state.step===2){result();return}state.step++;state.solved=false;state.selected=null;state.opened=[];state.zone=0;render();window.scrollTo(0,0)}
function result(){const b=data[state.bu];completed[state.bu]=true;try{localStorage.setItem('shift-completed',JSON.stringify(completed))}catch(e){}app.innerHTML=`<section class="result"><div class="seal">✓</div><div class="eyebrow" style="margin-top:24px">SHIFT COMPLETE / ${state.bu}</div><h1>呢一更，帶得好。</h1><p class="muted">你已完成三個任務及回饋。<br>首次選擇合適：${state.answers.filter(Boolean).length} / 3；所有關卡已完成合適處理。</p><div class="summary">${b.steps.map((q,i)=>`<div><span class="kicker">0${i+1} ${state.answers[i]?'一次掌握':'重試後掌握'}</span><p>${q.win}</p></div>`).join('')}</div><h2>下一更，帶返舖嘅一件事。</h2><p>${{WTCHK:'行一圈，留意邊個陳列影響同事視線同服務。',PNS:'同同事講清楚：繁忙時保持服務覆蓋，任何情況都唔好追逐。',FTR:'交代情況時，分開「見到嘅行為」同「未確認嘅判斷」。',WW:'同同事練一次友善開場，再練顧客拒絕後嘅安全做法。'}[state.bu]}</p><div class="actions"><button class="primary" onclick="start('${state.bu}')">再玩一次 ↻</button><button class="secondary" onclick="home()">試其他 BU →</button></div><div class="notice">呢個成果只係試玩版學習回饋，唔代表正式合格或 LMS 完成紀錄。BU 指定支援角色、次序及紀錄要求，需依已確認內部程序。</div></section>${footer()}`;window.scrollTo(0,0)}home();

const filmCopy={WTCHK:['先睇清楚：陳列有冇遮擋服務視線？','調整陳列，令同事更容易觀察同提供服務。'],PNS:['顧客似乎遇到付款問題，先了解情況。','「你好，我幫你核對一下付款狀態。」'],FTR:['留意實際商品處理動作；袋本身唔係證據。','以友善服務接觸，唔好未確認就指控。'],WW:['「你好，需要購物籃嗎？」','顧客拒絕亦保持尊重，留喺自然可見嘅服務位置。']};
function filmMarkup(bu){const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;return `<div class="film ${bu} ${reduced?'static':''}" aria-label="${bu} 寫實人物主題示範"><div class="film-top"><strong>主題示範 · 10 秒</strong><span>AI 擬真人物 · 非實拍</span></div><div class="film-screen"><div class="film-shot shot-one" role="img" aria-label="${filmCopy[bu][0]}"></div><div class="film-shot shot-two" role="img" aria-label="${filmCopy[bu][1]}"></div><div class="film-caption">${filmCopy[bu][0]}</div><div class="film-caption second">${filmCopy[bu][1]}</div></div><div class="film-progress"></div><div class="film-controls"><button class="film-toggle" ${reduced?'disabled':''} onclick="toggleFilm(this)">${reduced?'已按系統設定減少動態':'Ⅱ 暫停'}</button><button ${reduced?'disabled':''} onclick="replayFilm(this)">↻ 重播</button><span class="film-note">兩鏡頭動態示範 · 無聲亦可理解</span></div></div>`}
function toggleFilm(btn){const f=btn.closest('.film');if(f.classList.contains('static')||btn.dataset.ended){replayFilm(btn);return}const paused=f.classList.toggle('paused');btn.textContent=paused?'▶ 繼續':'Ⅱ 暫停';btn.setAttribute('aria-pressed',String(paused))}
function replayFilm(btn){let f=btn.closest('.film');f.classList.remove('paused','static');let fresh=f.cloneNode(true);fresh.querySelector('.film-toggle').textContent='Ⅱ 暫停';delete fresh.querySelector('.film-toggle').dataset.ended;f.replaceWith(fresh);bindFilm(fresh)}
function bindFilm(f){f.querySelector('.shot-two').addEventListener('animationend',()=>{const btn=f.querySelector('.film-toggle');btn.textContent='▶ 再睇一次';btn.dataset.ended='true'})}
const renderBase=render;render=function(){const prior=document.querySelector('.film');const same=prior&&prior.classList.contains(state.bu);renderBase();const photo=app.querySelector('.scene .retail-photo');if(photo){if(same)photo.replaceWith(prior);else{photo.outerHTML=filmMarkup(state.bu);bindFilm(app.querySelector('.film'))}}};
